Update Korean translation for pod (#3155)
According to the Korean l10n team's weekly meeting at 2018-07-24,
Korean translation of pod is changed from 팟 to 파드.

Exception: Both Korean and English will be used for the navigation
menu.